try:
    a = 1337 / 0
except Exception as erro:
    print("falha na execução, erro:", erro)
